<script setup>

import { RouterLink, RouterView } from 'vue-router'
import { createApp } from 'vue'
import MessagesList from './MessageList.vue';
import GroupList from './GroupList.vue';
import CurrentGroupHeader from './CurrentGroupHeader.vue';

</script>

<script>
export default 
{
  data() {
    return {
      custom_colors : ["0, 31, 84"],

      currentMessage: "",
      selectedConversationIndex : 0,

      myConversations : [
        { 
          picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI0IJvH3PBdBTEwR_UdWYYFkfSOBjHwPoW2g&s",
          name: "Avengers Private",
          messages: [
            { id: 0, username:"Juhasz",
              profilePic: "My profile pic",
              content: "Hello Everyone Im Juhasz! :)",
              timestamp: "10:23",
              sentByUser: true,
            },

            { id: 1, username:"Puppy",
              profilePic: "https://plus.unsplash.com/premium_photo-1694819488591-a43907d1c5cc?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3V0ZSUyMGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
              content: "Hello world! I'm a cat!",
              timestamp: "10:23",
              sentByUser: false,
            },

            { id: 2, username:"Batman",
              profilePic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTliobw0pREiVZRDG87AVEolPjxFnAK7V2S4Q&s",
              content: "I'm Batman!",
              timestamp: "10:24",
              sentByUser: false
            },
          ],
        },
        { 
          picture: "https://cdn.vertex42.com/ExcelTemplates/Images/college-class-schedule-template.png",
          name: "ACSAI 2022-2023",
          messages: [
            { id: 0, username:"Juhasz",
              profilePic: "My profile pic",
              content: "Hello Puppy! :)",
              timestamp: "10:23",
              sentByUser: true,
            },

            { id: 1, username:"Puppy",
              profilePic: "https://plus.unsplash.com/premium_photo-1694819488591-a43907d1c5cc?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3V0ZSUyMGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
              content: "Hello world! This is a long message generated by the admin of WasaText! :) Long messages are good for testing some properties of the messages :D",
              timestamp: "10:23",
              sentByUser: false,
            },
          ],
        },
        { 
          picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYpK7VpuX8sr6HECu375r-JS1R7jmbTgokoA&s",
          name: "WASA group",
          messages: [
            { id: 0, username:"Juhasz",
              profilePic: "My profile pic",
              content: "Hello Hello !",
              timestamp: "10:23",
              sentByUser: true,
            },

            { id: 1, username:"Puppy",
              profilePic: "https://plus.unsplash.com/premium_photo-1694819488591-a43907d1c5cc?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3V0ZSUyMGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
              content: "I'm a puppy!",
              timestamp: "10:23",
              sentByUser: false,
            },
          ],
        },
        { 
          picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbwRSOVyLRDN2_q2cFihbTI335rPAnZPQDHw&s", 
          name: "Animals",
          messages: [
            { id: 0, username:"Juhasz",
              profilePic: "My profile pic",
              content: "What a lovely week this will be!",
              timestamp: "10:23",
              sentByUser: true,
            },

            { id: 1, username:"Garfield",
              profilePic: "https://i.guim.co.uk/img/media/6b84d191353d5f505a76c4e2bfa4caed5387d7d2/102_0_1844_1107/master/1844.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=6b589d1a632c3af3523294eb45fd7ea2",
              content: "Oh no its monday again isnt it..",
              timestamp: "10:23",
              sentByUser: false,
            },
          ],
        },
      ],


    };
  },
  methods: {
      sendMessage(event) {
        if(event)
          event.preventDefault();

        if((this.currentMessage).trim() == ""){
          this.currentMessage = " ";
          return
        }

        const now = new Date();

        const hours = now.getHours().toString().padStart(2, "0");
        const minutes = now.getMinutes().toString().padStart(2, "0");

        // create a new message and push it to the messages
        const newMessage = {
          id: this.selectedConversation.messages.length,
          username: "You",
          profilePic: "My profile pic",
          content: this.currentMessage,
          timestamp: hours+":"+minutes,
          sentByUser: true,
        }
        
        this.selectedConversation.messages.push(newMessage);

        // reset textArea input
        this.currentMessage = "";

        this.$nextTick(() => {
          this.scrollToBottom(); // Scroll after DOM is updated
        });

      },
      scrollToBottom() {
        const scrollContainer = document.getElementById("MessagesList");
        scrollContainer.scrollTop = scrollContainer.scrollHeight; // Set scroll position to the bottom
      },
      resetCurrentText(){
        this.currentMessage = "";
      },
      SelectNewConversationInApp(index){
        console.log('Received notification:', index);
        this.selectedConversationIndex = index
      },
  },
  components: {
    MessagesList,
    GroupList,
    CurrentGroupHeader,
  },
  computed: {
    selectedConversation()
    {
      return this.myConversations[this.selectedConversationIndex];
    },
    currentMessageText()
    {
        return this.currentMessage;
    }
  }
}

</script>


<template>

	<header>
		<div id="header" style="background-color: rgb(50, 50, 50);">
			<div class="content">
        <h1>WasaText</h1>
      </div>
		</div>
	</header>

	<body style="background-color: rgb(50, 50, 50);">
    <div id="body" class="Flexbox">
      <div id="groupList">
        <GroupList :conversations="myConversations" @SelectNewConversation="SelectNewConversationInApp"/>
      </div>
      <div id="main">

        <CurrentGroupHeader id="CurrentGroupHeader"
          :picture=selectedConversation.picture
          :group-name=selectedConversation.name
          :member-count=4
        />

        <MessagesList id="MessagesList" :textMessages="this.selectedConversation.messages"/>

        <div id="TextAndSend" class="Flexbox" style="gap: 5px;">
          <textarea id="currentTextArea" v-model="currentMessage" placeholder="..." @keydown.enter="sendMessage"></textarea>
          <button id="sendButton" @click="sendMessage()"> Send </button>
        </div>

      </div>
    </div>

    <div id="pageFooter"> 
      <p style="text-align: center;"> Made by Barnabas Juhasz</p>
    </div>

  </body>

</template>

<style>

body, header, h1 {
	margin: 0;
	padding: 0;
}


#header {
  	padding-top: 1rem;
	text-align: center;
	height: 4rem;
  	color: rgb(146, 146, 146);
}


#groupList {
	display: block; 
	margin-left: auto;
	padding: 5px;
	width: 20vw;
	height: 70vh;
	border-radius: 15px;
	background-color: rgba(0, 0, 0, .5);
}

#main{
	display: flex; 
	margin-top: auto;
	margin-right: auto;
	padding: 5px;
	flex-direction: column;
	background-color: rgba(0, 0, 0, .25);
	height: 70vh;
	width: 70vw;
	border-radius: 15px;
}

#CurrentGroupHeader {
	display: flex;
	height: 75px;
	min-height: 75px;

	background-color: rgba(0, 0, 0, .5);
	margin-bottom: 5px;
	border-radius: 15px;
}

#MessagesList {
	display: block;
	margin-bottom: auto;
	overflow-y: auto;

  /*
  background-color: rgba(255, 0, 0, .25);
  flex-grow: 1;*/
}

#TextAndSend {
	margin-top: auto;
	margin-bottom: 0;
}

.Flexbox {
	display: flex;
	align-items: center;
	gap: 5px;
	
}


#currentTextArea {
	width: 60vw;
	height: 50px;
	margin: 0 auto;
	resize: none;
	border-radius: 15px;

	font-size: 50;

  	padding-left: 5px;
	padding-right: 5px;
	padding-top: 3px;
	padding-bottom: 3px;
}

#sendButton {
	width: 8vw;
	height: 40px;
	background-color: rgb(145, 224, 239);
	border-radius: 10px;
}

#pageFooter {
	height: 10vh;
  	color: rgb(146, 146, 146);
}


</style>