FROM golang:1.19.4 AS builder

### Copy Go code, copying required folders only (use .dockerignore)
WORKDIR /src/
COPY . .

RUN go build -o /app/webapi ./cmd/webapi

### Create final image
FROM debian:bookworm

### Inform Docker about which port is used
EXPOSE 3000

### Copy the build executable from the builder image
WORKDIR /app/
COPY --from=builder /app/webapi ./

### Executable command
CMD ["/app/webapi"]
