# Use latest Node LTS to build
FROM node:lts AS builder

### Copy actual frontend source code
WORKDIR /webui/
COPY webui .

### Build Vue.js into plain HTML/CSS/JS
RUN npm run build-prod

### Create final image
FROM nginx:stable

# Copy built frontend
COPY --from=builder /webui/dist/ /usr/share/nginx/html/
