openapi: 3.0.3
info:
  title: Simplified login API specification
  description: |-
    This OpenAPI document describes the simplified login API.
    Copy and paste the API from the `paths` key to your OpenAPI document.
  version: "1"
paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema: { $ref: "#/components/schemas/User" }
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    # change here if you decide to use an integer
                    # or any other type of identifier
                    type: string
                    example: "abcdef012345"
                    
  /session/{Username}:
    parameters:
      - $ref: "#/components/parameters/Username"
    put:
      summary: Set Username
      description: "Sets the username of the user"
      operationId: setMyUserName
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: Username updated successfully
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/User"
        "404": 
          description: User not found
          
  /session/{Username}/profilePicture:
    parameters:
      - $ref: "#/components/parameters/Username"
    put:
      summary: Set Profile Picture
      description: "Sets the profile picture of the user"
      operationId: setMyPhoto
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
            description: Profile Picture updated successfully
            content:
              application/json:
                schema: 
                  $ref: "#/components/schemas/User"
        "404": 
          description: User not found
        
  /session/{Username}/myConversations:
    parameters:
      - $ref: "#/components/parameters/Username"
    get:
      summary: get all of my conversations
      description: "Get all the conversations of the user"
      operationId: getMyConversations
      responses:
        "200":
          description: "My conversations fetched successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MyConversations"
        "404":
           description: User not found
          
components:
  schemas:
    User:
      description: "Object representing a User"
      type: object
      properties:
        Username:
          description: "a unique identifier of the user"
          type: string
          example: Maria
          pattern: 'ˆ.*?$'
          minLength: 3
          maxLength: 16
        Profile Picture:
          description: "the profile picture of the user"
    
    Group:
      description: "Object representing a Group of users"
      type: object
      properties:
        Group name:
          description: "name of the group"
          type: string
          example: Acsai Group
          pattern: 'ˆ.*?$'
          minLength: 3
          maxLength: 16
        Group Picture:
          description: "the picture of the group"
    
    Conversation:
      description: "Object representing a conversation"
      type: object
      properties:
        id:
          description: "unique identifier of a conversation"
          type: integer
        Conversation Type:
          description: "type of conversation, either with a single person or a group"
          type: string
          enum:
            - user
            - group
        Data:
          description: "content of the conversation -> a list of messages"
          type: object
          
    MyConversations:
      description: "Object representing all of my conversations"
      type: array
      items:
        $ref: "#/components/schemas/Conversation"
    
  parameters:
    Username:
      schema:
        type: string
        example: "abcdef012345"
        readOnly: true
      name: Username
      in: path
      required: true
      description: Unique Username
        
                      
      