
<script>
import MessagesList from '../components/MessageList.vue';
import GroupList from '../components/GroupList.vue';
import CurrentGroupHeader from '../components/CurrentGroupHeader.vue';
import CurrentProfile from '../components/CurrentProfile.vue';
import AddGroup from '../components/AddGroup.vue';

import { sharedData } from '../services/sharedData.js';

export default 
{
  setup() {
    // Log sharedData.UserSession when the component initializes
    console.log("Accessing UserSession in ConversationsView:", sharedData.UserSession);

    return {
      UserSession: sharedData.UserSession, // Bind UserSession for use in the template
    };
  },
  data() {
    return {
        custom_colors : ["0, 31, 84"],

        currentMessage: "",
        selectedConversationIndex : 0,
        myConversations : [
            { 
            picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTI0IJvH3PBdBTEwR_UdWYYFkfSOBjHwPoW2g&s",
            name: "Avengers Private",
            messages: [
                { id: 0, username:"Juhasz",
                profilePic: "My profile pic",
                content: "Hello Everyone Im Juhasz! :)",
                timestamp: "10:23",
                sentByUser: true,
                },

                { id: 1, username:"Puppy",
                profilePic: "https://plus.unsplash.com/premium_photo-1694819488591-a43907d1c5cc?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3V0ZSUyMGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
                content: "Hello world! I'm a cat!",
                timestamp: "10:23",
                sentByUser: false,
                },

                { id: 2, username:"Batman",
                profilePic: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTliobw0pREiVZRDG87AVEolPjxFnAK7V2S4Q&s",
                content: "I'm Batman!",
                timestamp: "10:24",
                sentByUser: false
                },
            ],
            },
            { 
            picture: "https://cdn.vertex42.com/ExcelTemplates/Images/college-class-schedule-template.png",
            name: "ACSAI 2022-2023",
            messages: [
                { id: 0, username:"Juhasz",
                profilePic: "My profile pic",
                content: "Hello Puppy! :)",
                timestamp: "10:23",
                sentByUser: true,
                },

                { id: 1, username:"Puppy",
                profilePic: "https://plus.unsplash.com/premium_photo-1694819488591-a43907d1c5cc?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3V0ZSUyMGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
                content: "Hello world! This is a long message generated by the admin of WasaText! :) Long messages are good for testing some properties of the messages :D",
                timestamp: "10:23",
                sentByUser: false,
                },
            ],
            },
            { 
            picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYpK7VpuX8sr6HECu375r-JS1R7jmbTgokoA&s",
            name: "WASA group",
            messages: [
                { id: 0, username:"Juhasz",
                profilePic: "My profile pic",
                content: "Hello Hello !",
                timestamp: "10:23",
                sentByUser: true,
                },

                { id: 1, username:"Puppy",
                profilePic: "https://plus.unsplash.com/premium_photo-1694819488591-a43907d1c5cc?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y3V0ZSUyMGRvZ3xlbnwwfHwwfHx8MA%3D%3D",
                content: "I'm a puppy!",
                timestamp: "10:23",
                sentByUser: false,
                },
            ],
            },
            { 
            picture: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbwRSOVyLRDN2_q2cFihbTI335rPAnZPQDHw&s", 
            name: "Animals",
            messages: [
                { id: 0, username:"Juhasz",
                profilePic: "My profile pic",
                content: "What a lovely week this will be!",
                timestamp: "10:23",
                sentByUser: true,
                },

                { id: 1, username:"Garfield",
                profilePic: "https://i.guim.co.uk/img/media/6b84d191353d5f505a76c4e2bfa4caed5387d7d2/102_0_1844_1107/master/1844.jpg?width=1200&height=900&quality=85&auto=format&fit=crop&s=6b589d1a632c3af3523294eb45fd7ea2",
                content: "Oh no its monday again isnt it..",
                timestamp: "10:23",
                sentByUser: false,
                },
            ],
            },
        ],

        

        };
    },
    methods: {
        sendMessage(event) {
            if(event)
            event.preventDefault();

            if((this.currentMessage).trim() == ""){
            this.currentMessage = "";
            return
            }

            const now = new Date();

            const hours = now.getHours().toString().padStart(2, "0"); // Ensure 2 digits
            const minutes = now.getMinutes().toString().padStart(2, "0");

            // create a new message and push it to the messages
            const newMessage = {
            id: this.selectedConversation.messages.length,
            username: "You",
            profilePic: "My profile pic",
            content: this.currentMessage,
            timestamp: hours+":"+minutes,
            sentByUser: true,
            }
            
            this.selectedConversation.messages.push(newMessage);

            // reset textArea input
            this.currentMessage = "";

            this.$nextTick(() => {
            this.scrollToBottom(); // Scroll after DOM is updated
            this.adjustHeight(); // Adjust the height of the text area after DOM is updated
            });

        },
        scrollToBottom() {
            const scrollContainer = document.getElementById("MessagesList");
            scrollContainer.scrollTop = scrollContainer.scrollHeight; // Set scroll position to the bottom
        },
        resetCurrentText(){
            this.currentMessage = "";
        },
        SelectNewConversationInApp(index){
            console.log('Received notification:', index);
            this.selectedConversationIndex = index
            this.currentMessage = "";

            this.$nextTick(() => {
            this.scrollToBottom(); // Scroll after DOM is updated
            this.adjustHeight(); // Adjust the height of the text area after DOM is updated
            });

        },
        adjustHeight() {
            const textarea = document.getElementById("currentTextArea");
            textarea.style.height = "auto";
            textarea.style.height = `${Math.min(textarea.scrollHeight, 200)}px`;
        },
    },
    mounted() {
    this.adjustHeight();
    },
    components: {
        MessagesList,
        GroupList,
        CurrentGroupHeader,
        CurrentProfile,
        AddGroup,
    },
    computed: {
      userSession() {
        return sharedData.UserSession;
      },
      selectedConversation()
      {
      return this.myConversations[this.selectedConversationIndex];
      },
      currentMessageText()
      {
          return this.currentMessage;
      },
    }
  }
</script>

<template>
    <div id="body" class="Flexbox">
        <div id="mainLeft">
            <div id="groupListParent">
            <GroupList :conversations="myConversations" @SelectNewConversation="SelectNewConversationInApp"/>
            </div>

            <div id="AddNewGroup">
            <AddGroup/>
            </div>

            <CurrentProfile
            -username= {{ userSession.Username }}
            -profile-picture="https://lh3.googleusercontent.com/a/ACg8ocIJ89svt7_3pYSx2J4hGwcpMA-AQ9oz2VEkpWQudHc1Gr1jgOuC=s260-c-no"
            />
        </div>  

        <div id="main">
            <CurrentGroupHeader id="CurrentGroupHeader"
            :picture=selectedConversation.picture
            :group-name=selectedConversation.name
            :member-count=4
            />

            <MessagesList id="MessagesList" :textMessages="this.selectedConversation.messages"/>

            <div id="TextAndSend" class="Flexbox" style="gap: 5px;">
                <textarea id="currentTextArea"
                rows="1"
                v-model="currentMessage"
                placeholder="Type a message"
                @keydown.enter="sendMessage"
                @input="adjustHeight"
                class="custom-scrollbar"
                ></textarea>

                <button id="sendButton" @click="sendMessage()" class="sendButtonImageContainer"> 

                    <img src="https://static-00.iconduck.com/assets.00/send-icon-2048x2020-jrvk5f1r.png"/>
                
                </button>
            </div>

        </div>
    </div>
</template>

<style>

body, header, h1 {
  margin: 0;
  padding: 0;
}


#header {
  padding-top: 1rem;
	text-align: center;
	height: 4rem;
  color: rgb(146, 146, 146);
}

#mainLeft {
  display: block; 
  margin-left: auto;
  height: 70vh;
  margin-top: 25px;
  width: 20vw;

}

#groupListParent {
  display: block; 
  margin-left: auto;
  padding: 5px;
  margin-top: 6px;
  height: calc(70vh - 65px - 46px);
  border-radius: 15px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
  background-color: rgba(0, 0, 0, 0.25);

  border: 3px solid rgba(0, 0, 0, .25);
  border-bottom: 0px;
}

#main{
  display: flex; 
  margin-top: auto;
  margin-right: auto;
  padding: 5px;
  flex-direction: column;
  background-color: rgba(0, 0, 0, .25);
  /*height: calc(70vh - 6px);*/
  height: calc(70vh - 6px);
  width: 70vw;
  border-radius: 15px;

  border: 3px solid rgba(0, 0, 0, .25);
}

#CurrentGroupHeader {
  display: flex;
  height: 75px;
  min-height: 75px;

  background-color: rgba(0, 0, 0, .5);
  margin-bottom: 5px;
  border-radius: 15px;
}

#MessagesList {
  display: block;
  margin-bottom: auto;
  overflow-y: auto;

  /*
  background-color: rgba(255, 0, 0, .25);
  flex-grow: 1;*/
}

#TextAndSend {
  margin-top: auto;
  margin-bottom: 0;
}

.Flexbox {
  display: flex;
  align-items: center;
  gap: 5px;
  
}


#currentTextArea {
  width: 100%;
  /*height: 15px;*/
  max-height: 100px;


  margin: 0;
  margin-top: 5px;
  resize: none;
  border-radius: 15px;
  border: 0;
  
  padding-left: 15px;
	padding-right: 20px;
	padding-top: 15px;
	padding-bottom: 15px;

  box-sizing: border-box; 

  background-color: rgb(75, 75, 75);
  outline: none;

  color: rgb(255, 255, 255);

}

#currentTextArea::placeholder {
    color: rgb(200, 200, 200);
}

.sendButtonImageContainer {
  padding: 5px;

  width: 30px;
  height: 30px;

	min-width: 30px;
	min-height: 30px;

  border-radius: 50%;
  overflow: hidden;
  display: flex;
  justify-content: center;
  align-items: center;

}

.sendButtonImageContainer img {
  width: 75%; 
  height: 75%;
  object-fit: cover;
}

#sendButton {
  width: 40px;
  height: 40px;
  min-width: 40px;
  min-height: 40px;
  background-color: rgb(255, 209, 0);
  border-radius: 15px;
  font-weight: bold;
  
  border: 0;
  outline: none;

  margin-top: auto;
  margin-bottom: 0;
}

#pageFooter {
	height: 10vh;
  color: rgb(146, 146, 146);
}





.custom-scrollbar::-webkit-scrollbar {
  width:2px;
  padding: 15px;
}


.custom-scrollbar::-webkit-scrollbar-track {
  background:rgba(28, 28, 28, 0);
  border-radius:15px;
  margin-bottom: 5px; /* Optional: Add spacing at the bottom */
}


.custom-scrollbar::-webkit-scrollbar-thumb {
  background:rgb(161, 161, 161);
  border-radius:15px;
}





</style>